# Generated by Django 3.0.7 on 2020-08-23 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('work_on', models.CharField(blank=True, choices=[('1', '10:00'), ('2', '11:00'), ('3', '12:00'), ('4', '13:00'), ('5', '14:00'), ('6', '15:00'), ('7', '16:00'), ('8', '17:00'), ('9', '18:00'), ('10', '19:00'), ('11', '20:00')], max_length=50, null=True, verbose_name='Рабочие часы')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_on', models.CharField(choices=[('1', '10:00'), ('2', '11:00'), ('3', '12:00'), ('4', '13:00'), ('5', '14:00'), ('6', '15:00'), ('7', '16:00'), ('8', '17:00'), ('9', '18:00'), ('10', '19:00'), ('11', '20:00')], max_length=50, verbose_name='Рабочие часы')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_organizer', models.BooleanField(default=False)),
                ('info_car', models.CharField(blank=True, max_length=30, null=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('second_name', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='userProfile',
        ),
        migrations.AddField(
            model_name='service',
            name='client_to_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.User', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Masters', verbose_name='Мастер'),
        ),
    ]
