# Generated by Django 3.0.7 on 2020-08-23 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200823_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masters',
            options={'verbose_name': 'Мастер', 'verbose_name_plural': 'Мастера'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Сервис', 'verbose_name_plural': 'Сервисы'},
        ),
        migrations.RemoveField(
            model_name='masters',
            name='work_on',
        ),
    ]
