# Generated by Django 3.0.7 on 2020-08-24 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0003_auto_20200823_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='client_to_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
