# Generated by Django 3.0.7 on 2020-08-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='second_name',
        ),
        migrations.AlterField(
            model_name='service',
            name='work_on',
            field=models.CharField(choices=[('1', '10:00'), ('2', '11:00'), ('3', '12:00'), ('4', '13:00'), ('5', '14:00'), ('6', '15:00'), ('7', '16:00'), ('8', '17:00'), ('9', '18:00'), ('10', '19:00'), ('11', '20:00')], max_length=30, verbose_name='Рабочие часы'),
        ),
    ]
